// <auto-generated />
using System;
using Goulash.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Goulash.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260928204141_EnforceSingleActiveDiscovery")]
    partial class EnforceSingleActiveDiscovery
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Goulash.Domain.AiProviderPromptSetting", b =>
                {
                    b.Property<string>("ProviderId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_id");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ProviderId");

                    b.ToTable("ai_provider_prompts", (string)null);

                    b.HasData(
                        new
                        {
                            ProviderId = "perplexity",
                            Prompt = "Follow the supplied two-stage supplier search instructions and return only the JSON object required by the schema.\nApply the user conditions in the initial list request. In profile requests, extract all available fields from the\nprovided company website pages and preserve useful source wording for price and order conditions.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        },
                        new
                        {
                            ProviderId = "polza",
                            Prompt = "Follow the supplied two-stage supplier search instructions and return only the JSON object required by the schema.\nUse live web search for the initial supplier list. For each profile request, use the supplied company website pages\nto extract all available details. Do not omit the company because some fields are unavailable.",
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0))
                        });
                });

            modelBuilder.Entity("Goulash.Domain.AiProviderSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("EncryptedApiKey")
                        .HasColumnType("bytea")
                        .HasColumnName("encrypted_api_key");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("model");

                    b.Property<string>("ProviderId")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("provider_id");

                    b.Property<string>("RouteProvider")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("route_provider");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("ai_provider_settings", null, t =>
                        {
                            t.HasCheckConstraint("ck_ai_provider_settings_singleton", "id = '00000000-0000-7000-8000-000000000001'");
                        });
                });

            modelBuilder.Entity("Goulash.Domain.DiscoveryRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AcceptedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("accepted_count");

                    b.Property<int>("CandidateCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("candidate_count");

                    b.Property<int>("CompletedCandidates")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("completed_candidates");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_code");

                    b.Property<int>("FailedProfileCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("failed_profile_count");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Outcome")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("outcome");

                    b.Property<string>("QueryJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("query_json");

                    b.Property<string>("ResultJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("result_json");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("stage");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("StartedAt")
                        .HasDatabaseName("ix_discovery_runs_started_at");

                    b.ToTable("discovery_runs", null, t =>
                        {
                            t.HasCheckConstraint("ck_discovery_runs_counts", "accepted_count >= 0 AND failed_profile_count >= 0");

                            t.HasCheckConstraint("ck_discovery_runs_status", "status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("Goulash.Domain.FactSource", b =>
                {
                    b.Property<Guid>("FactId")
                        .HasColumnType("uuid")
                        .HasColumnName("fact_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_id");

                    b.HasKey("FactId", "SourceId");

                    b.HasIndex("SourceId")
                        .HasDatabaseName("ix_fact_sources_source_id");

                    b.ToTable("fact_sources", (string)null);
                });

            modelBuilder.Entity("Goulash.Domain.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("city");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CurrentNameFactId")
                        .HasColumnType("uuid")
                        .HasColumnName("current_name_fact_id");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_favorite");

                    b.Property<DateTimeOffset?>("LastDiscoveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_discovered_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<string>("OfficialDomain")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("official_domain");

                    b.Property<string>("OfficialSiteUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("official_site_url");

                    b.Property<string>("Region")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("region");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("ix_suppliers_city");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_suppliers_created_at");

                    b.HasIndex("IsFavorite")
                        .HasDatabaseName("ix_suppliers_is_favorite");

                    b.HasIndex("OfficialDomain")
                        .IsUnique()
                        .HasDatabaseName("ux_suppliers_official_domain")
                        .HasFilter("official_domain IS NOT NULL");

                    b.HasIndex(new[] { "NormalizedName", "Region" }, "normalized_name_region")
                        .HasDatabaseName("ix_suppliers_normalized_name_region");

                    b.HasIndex(new[] { "NormalizedName", "Region" }, "undomained_normalized_name_region")
                        .HasDatabaseName("ix_suppliers_undomained_name_region")
                        .HasFilter("official_domain IS NULL");

                    b.ToTable("suppliers", null, t =>
                        {
                            t.HasCheckConstraint("ck_suppliers_name_nonempty", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("ck_suppliers_official_domain_normalized", "official_domain IS NULL OR (official_domain = lower(btrim(official_domain)) AND official_domain <> '')");
                        });
                });

            modelBuilder.Entity("Goulash.Domain.SupplierFact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FieldKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("field_key");

                    b.Property<bool>("IsCurrent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_current");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_key");

                    b.Property<string>("NormalizedValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("normalized_value_json");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("verification_status");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("ValueJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("value_json");

                    b.HasKey("Id");

                    b.HasAlternateKey("SupplierId", "Id")
                        .HasName("ak_supplier_facts_supplier_id_id");

                    b.HasIndex("SupplierId", "FieldKey", "ItemKey")
                        .IsUnique()
                        .HasDatabaseName("ux_supplier_facts_current_item")
                        .HasFilter("is_current");

                    b.HasIndex("SupplierId", "FieldKey", "ObservedAt")
                        .HasDatabaseName("ix_supplier_facts_history");

                    b.ToTable("supplier_facts", null, t =>
                        {
                            t.HasCheckConstraint("ck_supplier_facts_status", "verification_status IN ('official', 'external', 'ai_generated')");

                            t.HasCheckConstraint("ck_supplier_facts_value_object", "jsonb_typeof(value_json) <> 'null'");
                        });
                });

            modelBuilder.Entity("Goulash.Domain.SupplierImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FactId")
                        .HasColumnType("uuid")
                        .HasColumnName("fact_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("FactId");

                    b.HasIndex("SupplierId", "SortOrder")
                        .HasDatabaseName("ix_supplier_images_supplier_sort");

                    b.ToTable("supplier_images", null, t =>
                        {
                            t.HasCheckConstraint("ck_supplier_images_http_url", "url ~* '^https?://'");

                            t.HasCheckConstraint("ck_supplier_images_sort_order", "sort_order >= 0");
                        });
                });

            modelBuilder.Entity("Goulash.Domain.SupplierPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AmountMax")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_max");

                    b.Property<decimal>("AmountMin")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("amount_min");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<Guid>("FactId")
                        .HasColumnType("uuid")
                        .HasColumnName("fact_id");

                    b.Property<bool>("IsApproximate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_approximate");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("unit");

                    b.HasKey("Id");

                    b.HasIndex("FactId")
                        .IsUnique()
                        .HasDatabaseName("ux_supplier_prices_fact");

                    b.HasIndex("ProductId");

                    b.HasIndex("Currency", "Unit", "AmountMin", "AmountMax")
                        .HasDatabaseName("ix_supplier_prices_comparison");

                    b.ToTable("supplier_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_supplier_prices_amount_range", "amount_min >= 0 AND amount_max >= amount_min");

                            t.HasCheckConstraint("ck_supplier_prices_currency", "currency ~ '^[A-Z]{3}$'");
                        });
                });

            modelBuilder.Entity("Goulash.Domain.SupplierProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasColumnName("category");

                    b.Property<string>("ItemKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("item_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("normalized_name");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.HasKey("Id");

                    b.HasIndex("Category")
                        .HasDatabaseName("ix_supplier_products_category");

                    b.HasIndex("NormalizedName")
                        .HasDatabaseName("ix_supplier_products_normalized_name");

                    b.HasIndex("SupplierId", "ItemKey")
                        .IsUnique()
                        .HasDatabaseName("ux_supplier_products_supplier_item_key");

                    b.ToTable("supplier_products", null, t =>
                        {
                            t.HasCheckConstraint("ck_supplier_products_name_nonempty", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("Goulash.Domain.SupplierSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("excerpt");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("host");

                    b.Property<DateTimeOffset>("RetrievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("retrieved_at");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid")
                        .HasColumnName("supplier_id");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("source_type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "Url")
                        .HasDatabaseName("ix_supplier_sources_supplier_url");

                    b.ToTable("supplier_sources", null, t =>
                        {
                            t.HasCheckConstraint("ck_supplier_sources_excerpt_nonempty", "length(btrim(excerpt)) > 0");

                            t.HasCheckConstraint("ck_supplier_sources_http_url", "url ~* '^https?://' AND length(btrim(host)) > 0");

                            t.HasCheckConstraint("ck_supplier_sources_type", "source_type IN ('official', 'external')");
                        });
                });

            modelBuilder.Entity("Goulash.Domain.FactSource", b =>
                {
                    b.HasOne("Goulash.Domain.SupplierFact", "Fact")
                        .WithMany("FactSources")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fact_sources_fact");

                    b.HasOne("Goulash.Domain.SupplierSource", "Source")
                        .WithMany("FactSources")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fact_sources_source");

                    b.Navigation("Fact");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("Goulash.Domain.SupplierFact", b =>
                {
                    b.HasOne("Goulash.Domain.Supplier", "Supplier")
                        .WithMany("Facts")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_facts_supplier");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Goulash.Domain.SupplierImage", b =>
                {
                    b.HasOne("Goulash.Domain.SupplierFact", "Fact")
                        .WithMany("Images")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_images_fact");

                    b.HasOne("Goulash.Domain.Supplier", "Supplier")
                        .WithMany("Images")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_images_supplier");

                    b.Navigation("Fact");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Goulash.Domain.SupplierPrice", b =>
                {
                    b.HasOne("Goulash.Domain.SupplierFact", "Fact")
                        .WithMany("Prices")
                        .HasForeignKey("FactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_prices_fact");

                    b.HasOne("Goulash.Domain.SupplierProduct", "Product")
                        .WithMany("Prices")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_prices_product");

                    b.Navigation("Fact");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Goulash.Domain.SupplierProduct", b =>
                {
                    b.HasOne("Goulash.Domain.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_products_supplier");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Goulash.Domain.SupplierSource", b =>
                {
                    b.HasOne("Goulash.Domain.Supplier", "Supplier")
                        .WithMany("Sources")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_sources_supplier");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Goulash.Domain.Supplier", b =>
                {
                    b.Navigation("Facts");

                    b.Navigation("Images");

                    b.Navigation("Products");

                    b.Navigation("Sources");
                });

            modelBuilder.Entity("Goulash.Domain.SupplierFact", b =>
                {
                    b.Navigation("FactSources");

                    b.Navigation("Images");

                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Goulash.Domain.SupplierProduct", b =>
                {
                    b.Navigation("Prices");
                });

            modelBuilder.Entity("Goulash.Domain.SupplierSource", b =>
                {
                    b.Navigation("FactSources");
                });
#pragma warning restore 612, 618
        }
    }
}
